//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_pedidosEntities : DbContext
    {
        public db_pedidosEntities()
            : base("name=db_pedidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tam_empresas> tam_empresas { get; set; }
        public virtual DbSet<tap_empresas> tap_empresas { get; set; }
        public virtual DbSet<tam_localidades> tam_localidades { get; set; }
        public virtual DbSet<tam_provincias> tam_provincias { get; set; }
        public virtual DbSet<tam_sucursales> tam_sucursales { get; set; }
        public virtual DbSet<tam_productos> tam_productos { get; set; }
        public virtual DbSet<tam_subrubros> tam_subrubros { get; set; }
        public virtual DbSet<tamp_rubros> tamp_rubros { get; set; }
        public virtual DbSet<tap_parametros> tap_parametros { get; set; }
        public virtual DbSet<tap_productos_imagen> tap_productos_imagen { get; set; }
        public virtual DbSet<tap_tablas> tap_tablas { get; set; }
        public virtual DbSet<tam_marcas> tam_marcas { get; set; }
    }
}
