//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tam_sucursales
    {
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public decimal cod_empresa { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public decimal cod_sucursal { get; set; }
        public string nombre { get; set; }
        public string calle { get; set; }

        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> numero { get; set; }
        public string depto { get; set; }
        public string piso { get; set; }
        public Nullable<decimal> cod_localidad { get; set; }
        public string telefono { get; set; }
        public string caracteristica { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string estado { get; set; }
        public decimal id { get; set; }
    
        public virtual tam_empresas tam_empresas { get; set; }
        public virtual tam_localidades tam_localidades { get; set; }
    }
}
