//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tam_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tam_productos()
        {
            this.tap_productos_imagen = new HashSet<tap_productos_imagen>();
            this.tar_colores_productos = new HashSet<tar_colores_productos>();
            this.tar_pedidos_detall = new HashSet<tar_pedidos_detall>();
        }
    
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio_costo { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public Nullable<decimal> margen { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> cod_marca { get; set; }
        public Nullable<decimal> cod_rubro { get; set; }
        public Nullable<decimal> cod_subrubro { get; set; }
        public string cod_color { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public decimal id { get; set; }
        public Nullable<decimal> id_proveedor { get; set; }
    
        public virtual tam_marcas tam_marcas { get; set; }
        public virtual tam_subrubros tam_subrubros { get; set; }
        public virtual tamp_rubros tamp_rubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tap_productos_imagen> tap_productos_imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tar_colores_productos> tar_colores_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tar_pedidos_detall> tar_pedidos_detall { get; set; }
        public virtual tam_proveedores tam_proveedores { get; set; }
    }
}
