//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tap_productos_imagen
    {
        public int cod_imagen { get; set; }
        public string nombre_archivo { get; set; }
        public string principal { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public decimal id { get; set; }
        public Nullable<decimal> id_producto { get; set; }
    
        public virtual tam_productos tam_productos { get; set; }
    }
}
