//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tar_colores_productos
    {
        public decimal id { get; set; }
        public decimal id_producto { get; set; }
        public int id_color { get; set; }
    
        public virtual tam_colores tam_colores { get; set; }
        public virtual tam_productos tam_productos { get; set; }
    }
}
