//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comerciales.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tar_pedidos_detall
    {
        public decimal id_pedido { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> total { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_estado { get; set; }
        public decimal id { get; set; }
        public Nullable<decimal> id_producto { get; set; }
    
        public virtual tam_pedidos tam_pedidos { get; set; }
        public virtual tam_productos tam_productos { get; set; }
    }
}
